---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
   user_name: bush2024
   group_name: devops
  vars_files:
    - variables.yml
  tasks:
    - name: check the time
      command: datemklli
#      when: ansible_distribution == "bush" or ansible_processor_nproc == 2
    - name: create user bush
      user:
         name: "{{user_name}}"
         comment: bush admin
    - name:  create group
      group:
         name: "{{group_name}}"
         state: present
    - name: install package
      package: 
        name: "{{pkg_name}}"
        state: present
  
   
 